-- SQL Seed Data
-- Generated from seed/const.ts

-- Seeding 110 JobCategories
INSERT INTO "JobCategory" ("name") VALUES
  ('Web Development'),
  ('Mobile Development'),
  ('Backend Engineering'),
  ('Frontend Engineering'),
  ('Full Stack Development'),
  ('Game Development'),
  ('Embedded Systems'),
  ('Systems Engineering'),
  ('Platform Engineering'),
  ('DevOps & Infrastructure'),
  ('Data Engineering'),
  ('Machine Learning Engineering'),
  ('Artificial Intelligence'),
  ('Business Intelligence'),
  ('Data Analytics'),
  ('Big Data'),
  ('MLOps'),
  ('Applied Research'),
  ('Quantitative Analysis'),
  ('Cloud Computing'),
  ('Cloud Architecture'),
  ('Cybersecurity'),
  ('Information Security'),
  ('Network Engineering'),
  ('Site Reliability Engineering'),
  ('IT Operations'),
  ('IT Support'),
  ('IT Governance'),
  ('Product Management'),
  ('Product Strategy'),
  ('Program Management'),
  ('Project Management'),
  ('Technical Program Management'),
  ('Business Analysis'),
  ('Digital Transformation'),
  ('Innovation Management'),
  ('UX Research'),
  ('UI Design'),
  ('Interaction Design'),
  ('Product Design'),
  ('Visual Design'),
  ('Graphic Design'),
  ('Motion Design'),
  ('Brand Design'),
  ('Content Design'),
  ('Growth Marketing'),
  ('Performance Marketing'),
  ('Content Marketing'),
  ('Email Marketing'),
  ('Social Media Marketing'),
  ('Search Engine Optimization'),
  ('Search Engine Marketing'),
  ('Marketing Analytics'),
  ('Brand Management'),
  ('Public Relations'),
  ('Business Development'),
  ('Enterprise Sales'),
  ('Inside Sales'),
  ('Sales Operations'),
  ('Account Management'),
  ('Customer Success'),
  ('Partnerships'),
  ('Revenue Operations'),
  ('Channel Sales'),
  ('Customer Experience'),
  ('Customer Operations'),
  ('Technical Support'),
  ('Service Operations'),
  ('Field Support'),
  ('Incident Management'),
  ('Service Delivery'),
  ('Talent Acquisition'),
  ('People Operations'),
  ('Employee Experience'),
  ('Learning & Development'),
  ('Organizational Development'),
  ('Compensation & Benefits'),
  ('Workforce Planning'),
  ('Diversity & Inclusion'),
  ('Financial Planning & Analysis'),
  ('Accounting'),
  ('Payroll'),
  ('Treasury'),
  ('Risk Management'),
  ('Compliance'),
  ('Audit'),
  ('Taxation'),
  ('Legal Operations'),
  ('Contract Management'),
  ('E-commerce'),
  ('Marketplace Operations'),
  ('Supply Chain'),
  ('Logistics'),
  ('Procurement'),
  ('Vendor Management'),
  ('Operations Management'),
  ('EdTech'),
  ('Corporate Training'),
  ('Instructional Design'),
  ('Academic Research'),
  ('Technical Writing'),
  ('Knowledge Management'),
  ('Content Creation'),
  ('Copywriting'),
  ('Editorial'),
  ('Journalism'),
  ('Media Production'),
  ('Video Production'),
  ('Podcasting'),
  ('Community Management')
ON CONFLICT DO NOTHING;

-- Seeding 329 Skills
INSERT INTO "Skill" ("name") VALUES
  ('TypeScript'),
  ('JavaScript'),
  ('Python'),
  ('React'),
  ('Node.js'),
  ('PostgreSQL'),
  ('Docker'),
  ('AWS'),
  ('UI/UX Design'),
  ('SEO'),
  ('Project Management'),
  ('Machine Learning'),
  ('GraphQL'),
  ('Kubernetes'),
  ('Distributed Systems'),
  ('Event-Driven Architecture'),
  ('Domain-Driven Design'),
  ('CQRS'),
  ('Event Sourcing'),
  ('High Availability'),
  ('Scalability Engineering'),
  ('Load Balancing'),
  ('Caching Strategies'),
  ('Fault Tolerance'),
  ('API Gateway'),
  ('API Versioning'),
  ('Rate Limiting'),
  ('Webhooks'),
  ('OpenAPI Specification'),
  ('Swagger'),
  ('Postman'),
  ('Insomnia'),
  ('Third-Party Integrations'),
  ('Payment Gateway Integration'),
  ('Apache Kafka'),
  ('RabbitMQ'),
  ('ActiveMQ'),
  ('Amazon SQS'),
  ('Amazon SNS'),
  ('Google Pub/Sub'),
  ('Apache Pulsar'),
  ('Message Queues'),
  ('Stream Processing'),
  ('Logging'),
  ('Monitoring'),
  ('Alerting'),
  ('Tracing'),
  ('Prometheus'),
  ('Grafana'),
  ('Datadog'),
  ('New Relic'),
  ('Sentry'),
  ('Elastic APM'),
  ('Site Reliability Engineering'),
  ('Webpack'),
  ('Vite'),
  ('Rollup'),
  ('Parcel'),
  ('Babel'),
  ('ESLint'),
  ('Prettier'),
  ('Husky'),
  ('Lint-Staged'),
  ('NPM'),
  ('Yarn'),
  ('PNPM'),
  ('Linux'),
  ('Unix'),
  ('Windows Server'),
  ('Shell Scripting'),
  ('Bash'),
  ('Zsh'),
  ('TCP/IP'),
  ('HTTP/HTTPS'),
  ('DNS'),
  ('CDN Management'),
  ('Nginx'),
  ('Apache'),
  ('WordPress'),
  ('Headless CMS'),
  ('Strapi'),
  ('Contentful'),
  ('Sanity'),
  ('Ghost'),
  ('Shopify'),
  ('WooCommerce'),
  ('Magento'),
  ('BigCommerce'),
  ('Payment Processing'),
  ('Unity'),
  ('Unreal Engine'),
  ('Game Development'),
  ('2D Game Design'),
  ('3D Modeling'),
  ('OpenGL'),
  ('WebGL'),
  ('Shader Programming'),
  ('Physics Engines'),
  ('JavaScript'),
  ('TypeScript'),
  ('Python'),
  ('Java'),
  ('C'),
  ('C++'),
  ('C#'),
  ('Go'),
  ('Rust'),
  ('PHP'),
  ('Ruby'),
  ('Swift'),
  ('Kotlin'),
  ('Dart'),
  ('R'),
  ('MATLAB'),
  ('Scala'),
  ('Perl'),
  ('Haskell'),
  ('Lua'),
  ('HTML5'),
  ('CSS3'),
  ('Sass'),
  ('Less'),
  ('Tailwind CSS'),
  ('Bootstrap'),
  ('Material UI'),
  ('React'),
  ('Next.js'),
  ('Vue.js'),
  ('Nuxt.js'),
  ('Angular'),
  ('Svelte'),
  ('Redux'),
  ('Zustand'),
  ('MobX'),
  ('jQuery'),
  ('Web Components'),
  ('Storybook'),
  ('Node.js'),
  ('Express.js'),
  ('NestJS'),
  ('Fastify'),
  ('Django'),
  ('Flask'),
  ('FastAPI'),
  ('Spring Boot'),
  ('ASP.NET'),
  ('Laravel'),
  ('Symfony'),
  ('Ruby on Rails'),
  ('GraphQL'),
  ('REST APIs'),
  ('gRPC'),
  ('Microservices'),
  ('PostgreSQL'),
  ('MySQL'),
  ('MariaDB'),
  ('SQLite'),
  ('MongoDB'),
  ('Cassandra'),
  ('Redis'),
  ('DynamoDB'),
  ('Firebase'),
  ('Firestore'),
  ('Elasticsearch'),
  ('Neo4j'),
  ('InfluxDB'),
  ('AWS'),
  ('Azure'),
  ('Google Cloud Platform'),
  ('Docker'),
  ('Docker Compose'),
  ('Kubernetes'),
  ('Helm'),
  ('Terraform'),
  ('Pulumi'),
  ('Ansible'),
  ('Jenkins'),
  ('GitHub Actions'),
  ('GitLab CI'),
  ('CircleCI'),
  ('ArgoCD'),
  ('Serverless'),
  ('React Native'),
  ('Flutter'),
  ('SwiftUI'),
  ('UIKit'),
  ('Android SDK'),
  ('Jetpack Compose'),
  ('Ionic'),
  ('Xamarin'),
  ('Machine Learning'),
  ('Deep Learning'),
  ('Data Science'),
  ('Data Analysis'),
  ('Pandas'),
  ('NumPy'),
  ('SciPy'),
  ('Scikit-learn'),
  ('TensorFlow'),
  ('PyTorch'),
  ('Keras'),
  ('OpenCV'),
  ('Natural Language Processing'),
  ('Computer Vision'),
  ('MLOps'),
  ('Data Visualization'),
  ('Power BI'),
  ('Tableau'),
  ('Unit Testing'),
  ('Integration Testing'),
  ('End-to-End Testing'),
  ('Jest'),
  ('Mocha'),
  ('Chai'),
  ('Vitest'),
  ('Cypress'),
  ('Playwright'),
  ('Selenium'),
  ('Testing Library'),
  ('QA Automation'),
  ('Web Security'),
  ('OWASP'),
  ('Authentication'),
  ('Authorization'),
  ('OAuth'),
  ('JWT'),
  ('SSO'),
  ('Penetration Testing'),
  ('Cryptography'),
  ('Network Security'),
  ('Application Security'),
  ('UI Design'),
  ('UX Design'),
  ('User Research'),
  ('Wireframing'),
  ('Prototyping'),
  ('Figma'),
  ('Sketch'),
  ('Adobe XD'),
  ('Design Systems'),
  ('Accessibility'),
  ('Usability Testing'),
  ('Git'),
  ('GitFlow'),
  ('Monorepos'),
  ('Nx'),
  ('Turborepo'),
  ('Agile'),
  ('Scrum'),
  ('Kanban'),
  ('CI/CD'),
  ('Code Review'),
  ('Refactoring'),
  ('Clean Code'),
  ('System Design'),
  ('Project Management'),
  ('Product Management'),
  ('Stakeholder Management'),
  ('Technical Writing'),
  ('Documentation'),
  ('Mentoring'),
  ('Leadership'),
  ('Problem Solving'),
  ('Critical Thinking'),
  ('Communication'),
  ('Time Management'),
  ('Team Collaboration'),
  ('Remote Work'),
  ('SEO'),
  ('SEM'),
  ('Google Analytics'),
  ('A/B Testing'),
  ('Conversion Rate Optimization'),
  ('Content Strategy'),
  ('Email Marketing'),
  ('Social Media Marketing'),
  ('Blockchain'),
  ('Smart Contracts'),
  ('Solidity'),
  ('Ethereum'),
  ('Polygon'),
  ('Web3.js'),
  ('Ethers.js'),
  ('NFT Development'),
  ('DeFi'),
  ('Cryptography Protocols'),
  ('Prompt Engineering'),
  ('AI Model Fine-Tuning'),
  ('Chatbot Development'),
  ('Recommendation Systems'),
  ('Robotic Process Automation'),
  ('Workflow Automation'),
  ('AutoML'),
  ('Feature Engineering'),
  ('ETL Pipelines'),
  ('ELT Pipelines'),
  ('Apache Airflow'),
  ('Apache Spark'),
  ('Hadoop'),
  ('Data Warehousing'),
  ('Snowflake'),
  ('BigQuery'),
  ('Redshift'),
  ('Data Governance'),
  ('GDPR Compliance'),
  ('HIPAA Compliance'),
  ('SOC 2'),
  ('ISO 27001'),
  ('Data Privacy'),
  ('Risk Assessment'),
  ('Regulatory Reporting'),
  ('Performance Tuning'),
  ('Memory Optimization'),
  ('CPU Profiling'),
  ('Network Optimization'),
  ('Lighthouse Audits'),
  ('Core Web Vitals'),
  ('Cross-Functional Collaboration'),
  ('Requirements Gathering'),
  ('Technical Interviews'),
  ('Sprint Planning'),
  ('Backlog Grooming'),
  ('Release Management'),
  ('Change Management'),
  ('Production Support'),
  ('Incident Management'),
  ('Root Cause Analysis'),
  ('On-Call Rotation'),
  ('Service Desk Operations')
ON CONFLICT DO NOTHING;
